#!/bin/bash -x

shopt -s extglob

read -p"enter pass: "  s
if [[  ${#s} -ge 8 &&  "$s" == *[[:upper:]]* && "$s" == *[\+\-\#\$\@\%]* && "$s" == *[a-z]* && "$s" == *[0-9]* ]]
then
    echo "pass"
else
    echo "fail"
fi

